services:
  postgres-exporter-master:
    image: prometheuscommunity/postgres-exporter
    environment:
      - DATA_SOURCE_NAME=postgresql://app_user:app_password@postgres-master:5432/app_db?sslmode=disable
    ports:
      - "9187:9187"
    depends_on:
      postgres-master:
        condition: service_healthy
    networks:
      - otus

  postgres-exporter-slave-1:
    image: prometheuscommunity/postgres-exporter
    environment:
      - DATA_SOURCE_NAME=postgresql://app_user:app_password@postgres-slave-1:5432/app_db?sslmode=disable
    ports:
      - "9188:9187"
    depends_on:
      postgres-slave-1:
        condition: service_healthy
    networks:
      - otus

  prometheus:
    image: prom/prometheus
    volumes:
      - ./etc/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - postgres-exporter-master
      - postgres-exporter-slave-1
      - postgres-exporter-slave-2
    networks:
      - otus

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - otus
