db:
  master:
    host: "localhost"
    port: 5440
    user: "test_user"
    password: "test_password"
    dbname: "social_test"
  replicas: []

redis:
  host: "localhost"
  port: 6380
  password: ""
  db: 0

backend:
  port: 8080
  host: "0.0.0.0"

rabbitmq:
  url: "amqp://guest:guest@localhost:5673/"